/**:
  ros__parameters:
    links_map:
      base: base_link
      left_front:
        - 13_Link
        - 12_Link
        - 11_Link
        - 10_Link

      right_front:
        - 23_Link
        - 22_Link
        - 21_Link
        - 20_Link

      left_hind:
        - 43_Link
        - 42_Link
        - 41_Link
        - 40_Link

      right_hind:
        - 33_Link
        - 32_Link
        - 31_Link
        - 30_Link